name: vibe_music_app
description: A music player app for Vibe Music Server

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.1.0
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  just_audio: ^0.9.35
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^2.4.1
  get: 5.0.0-release-candidate-9.3.2
  dio: 5.8.0+1
  image_picker: ^1.0.7
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env